# Config file for travis-ci.org

language: python

# Python versions to test
python:
    - "2.7"

install:
    - "sudo apt-get install cython netcdf-bin libnetcdf-dev libhdf5-serial-dev"
    - "pip install --upgrade -r requirements.txt"

script: "cd test && py.test"

